export const Actions = {
	FETCH_OFFERS: 'FETCH_OFFERS',
	FETCH_FAVORITES_OFFERS: 'FETCH_FAVORITES_OFFERS',
	CHANGE_CITY: 'CHANGE_CITY',
	CHANGE_SORT_VARIANT: 'CHANGE_SORT_VARIANT',
	CHECK_AUTH_STATUS: 'CHECK_AUTH_STATUS',
	AUTHORIZE: 'AUTHORIZE',
	LOGOUT: 'LOGOUT'
};
